### ISSUE TITLE
ERR Cannot inspect image from service 

### ISSUE THREAD

**Issue by margaale** [crazy-max/diun#52] opened 2020-03-25 12:22 UTC
### Behaviour

Using a swarm with 2 nodes, one master and one slave both running on a raspberry. When te cron task is executed there is an error in the logs. 

#### Steps to reproduce this issue

1. Install diun
2. Run it with default config

#### Expected behaviour

> It should inspect the registry and notificate if there is a new version

#### Actual behaviour

> I see an error saying the service cannot be inspected

### Configuration

* Diun version :  2.5.0
* Platform (windows/linux) : linux arm
* System info (type `uname -a`) : Linux raspi02 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux

``` dockercompose.yml

   diun:
    image: crazymax/diun
    environment:
      - "TZ=America/Argentina/Buenos_Aires"
      - "LOG_LEVEL=debug"
      - "LOG_JSON=false"
      - "LOG_CALLER=true"
    volumes:
      - "/mnt/myvol1/diun/data:/data"
      - "/mnt/myvol1/diun/config/diun.yml:/diun.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - node.role == manager
```

```yml
# paste your YAML configuration file here and remove sensitive data
watch:
  workers: 20
  schedule: "*/30 * * * *"

providers:
  swarm:
   myswarm:
     watch_by_default: true

notif:
  slack:
    enable: true
    webhook: webhoolk
```
### Logs
```
# paste logs here (set log-level to debug and enable log-caller)
^[[90mWed, 25 Mar 2020 09:28:58 -03^[[0m ^[[33mDBG^[[0m ^[[1mapp/internal/db/client.go:42^[[0m^[[36m >^[[0m 435 entries found in database
^[[90mWed, 25 Mar 2020 09:28:58 -03^[[0m ^[[33mDBG^[[0m ^[[1mapp/internal/notif/client.go:50^[[0m^[[36m >^[[0m 1 notifier(s) created
^[[90mWed, 25 Mar 2020 09:28:58 -03^[[0m ^[[32mINF^[[0m ^[[1mapp/internal/app/diun.go:101^[[0m^[[36m >^[[0m Cron triggered
^[[90mWed, 25 Mar 2020 09:28:58 -03^[[0m ^[[32mINF^[[0m ^[[1mapp/internal/provider/swarm/swarm.go:30^[[0m^[[36m >^[[0m Found 1 swarm provider(s) to analyze...
^[[90mWed, 25 Mar 2020 09:28:58 -03^[[0m ^[[33mDBG^[[0m ^[[1mapp/internal/provider/swarm/service.go:43^[[0m^[[36m >^[[0m Skip locally built image for service ojkg5dtq3vgbsvwmfqccsvs4z ^[[36mprovider=^[[0mswarm-myswarm
^[[90mWed, 25 Mar 2020 09:28:58 -03^[[0m ^[[1m^[[31mERR^[[0m^[[0m ^[[1mapp/internal/provider/swarm/service.go:40^[[0m^[[36m >^[[0m Cannot inspect image from service go8rtrp70eoq19fi334fq1j3w ^[[31merror=^[[0m^[[31m"Error: No such image: authelia/authelia:4@sha256:ac141ef823a4a220d90d4e920fc6725141d1a1793a1aa33d82d2c555afd70a31"^[[0m ^[[36mprovider=^[[0mswarm-myswarm
^[[90mWed, 25 Mar 2020 09:28:58 -03^[[0m ^[[1m^[[31mERR^[[0m^[[0m ^[[1mapp/internal/provider/swarm/service.go:40^[[0m^[[36m >^[[0m Cannot inspect image from service lw4bkkllwqfp1r3f1e3vnzje4 ^[[31merror=^[[0m^[[31m"Error: No such image: oliver006/redis_exporter:latest-arm@sha256:aeafc14acc840675efecb1404d644ca936b10f6c5e1884bb1ea8359fbb75d3c6"^[[0m ^[[36mprovider=^[[0mswarm-myswarm
^[[90mWed, 25 Mar 2020 09:28:58 -03^[[0m ^[[33mDBG^[[0m ^[[1mapp/internal/logging/logger.go:68^[[0m^[[36m >^[[0m [containers/image] reference rewritten from 'docker.io/portainer/agent:latest' to 'doc
```

**Comment by margaale** [comment] 2020-03-25 12:37
As far as i can tell, the images that cannot be inspected are the ones that are downloaded and being run in the other node

**Comment by crazy-max** [comment] 2020-03-25 13:45
@margaale Thanks for your input, I will take a look on this.

**Comment by crazy-max** [comment] 2020-03-25 22:22
@margaale Yep it's a bug. It will be fixed soon. Thanks for your input.

**Comment by crazy-max** [comment] 2020-03-26 02:18
@margaale Should be ok now

**Closed by crazy-max** 2020-03-26 02:18 UTC
Labels: :bug: bug

**Comment by margaale** [comment] 2020-03-26 02:26
Now I'm seeing:
``` 
Actions  
      
Wed, 25 Mar 2020 23:23:39 -03 INF Starting Diun 2.6.0


Wed, 25 Mar 2020 23:23:40 -03 INF Cron triggered


Wed, 25 Mar 2020 23:23:40 -03 INF Found 1 swarm provider(s) to analyze...


Wed, 25 Mar 2020 23:23:44 -03 ERR Cannot run job error="Error choosing image instance: no image found in manifest list for architecture amd64, variant v7, OS linux" provider=swarm-myswarm


Wed, 25 Mar 2020 23:23:44 -03 ERR Cannot run job error="Error choosing image instance: no image found in manifest list for architecture amd64, variant v7, OS linux" provider=swarm-myswarm


Wed, 25 Mar 2020 23:23:44 -03 ERR Cannot run job error="Error choosing image instance: no image found in manifest list for architecture amd64, variant v7, OS linux" provider=swarm-myswarm


Wed, 25 Mar 2020 23:23:44 -03 ERR Cannot run job error="Error choosing image instance: no image found in manifest list for architecture amd64, variant v7, OS linux" provider=swarm-myswarm


Wed, 25 Mar 2020 23:23:44 -03 ERR Cannot run job error="Error choosing image instance: no image found in manifest list for architecture amd64, variant v7, OS linux" provider=swarm-myswarm


Wed, 25 Mar 2020 23:23:44 -03 ERR Cannot run job error="Error choosing image instance: no image found in manifest list for architecture amd64, variant v7, OS linux" provider=swarm-myswarm


Wed, 25 Mar 2020 23:23:44 -03 ERR Cannot run job error="Error choosing image instance: no image found in manifest list for architecture amd64, variant v7, OS linux" provider=swarm-myswarm


Wed, 25 Mar 2020 23:23:44 -03 ERR Cannot run job error="Error choosing image instance: no image found in manifest list for architecture amd64, variant v7, OS linux" provider=swarm-myswarm


Wed, 25 Mar 2020 23:23:45 -03 ERR Cannot list tags from registry error="Error choosing image instance: no image found in manifest list for architecture amd64, variant v7, OS linux" image=grafana/grafana:6.7.1 provider=swarm-myswarm


Wed, 25 Mar 2020 23:23:48 -03 ERR Cannot run job error="Error choosing image instance: no image found in manifest list for architecture amd64, variant v7, OS linux" provider=swarm-myswarm


Wed, 25 Mar 2020 23:23:48 -03 ERR Cannot run job error="Error choosing image instance: no image found in manifest list for architecture amd64, variant v7, OS linux" provider=swarm-myswarm


Wed, 25 Mar 2020 23:23:48 -03 ERR Cannot run job error="Error choosing image instance: no image found in manifest list for architecture amd64, variant v7, OS linux" provider=swarm-myswarm


Wed, 25 Mar 2020 23:23:48 -03 ERR Cannot run job error="Error choosing image instance: no image found in manifest list for architecture amd64, variant v7, OS linux" provider=swarm-myswarm


Wed, 25 Mar 2020 23:23:48 -03 ERR Cannot run job error="Error choosing image instance: no image found in manifest list for architecture amd64, variant v7, OS linux" provider=swarm-myswarm


Wed, 25 Mar 2020 23:23:48 -03 ERR Cannot run job error="Error choosing image instance: no image found in manifest list for architecture amd64, variant v7, OS linux" provider=swarm-myswarm


Wed, 25 Mar 2020 23:23:48 -03 ERR Cannot run job error="Error choosing image instance: no image found in manifest list for architecture amd64, variant v7, OS linux" provider=swarm-myswarm


Wed, 25 Mar 2020 23:23:48 -03 ERR Cannot run job error="Error choosing image instance: no image found in manifest list for architecture amd64, variant v7, OS linux" provider=swarm-myswarm


Wed, 25 Mar 2020 23:23:48 -03 ERR Cannot run job error="Error choosing image instance: no image found in manifest list for architecture amd64, variant v7, OS linux" provider=swarm-myswarm


Wed, 25 Mar 2020 23:23:48 -03 ERR Cannot run job error="Error choosing image instance: no image found in manifest list for architecture amd64, variant v7, OS linux" provider=swarm-myswarm


Wed, 25 Mar 2020 23:23:48 -03 ERR Cannot run job error="Error choosing image instance: no image found in manifest list for architecture amd64, variant v7, OS linux" provider=swarm-myswarm


Wed, 25 Mar 2020 23:23:48 -03 ERR Cannot run job error="Error choosing image instance: no image found in manifest list for architecture amd64, variant v7, OS linux" provider=swarm-myswarm


Wed, 25 Mar 2020 23:23:48 -03 ERR Cannot run job error="Error choosing image instance: no image found in manifest list for architecture amd64, variant v7, OS linux" provider=swarm-myswarm


Wed, 25 Mar 2020 23:23:48 -03 ERR Cannot run job error="Error choosing image instance: no image found in manifest list for architecture amd64, variant v7, OS linux" provider=swarm-myswarm


Wed, 25 Mar 2020 23:23:50 -03 INF Cron initialized with schedule */30 * * * *


Wed, 25 Mar 2020 23:23:50 -03 INF Next run in 6 minutes (2020-03-25 23:30:00 -0300 -03)

```

**Comment by margaale** [comment] 2020-03-26 02:27
Should I change the architecture ?

**Comment by crazy-max** [comment] 2020-03-26 09:56
Yes you should. Default values are currently `linux/amd64` but maybe we could detect the current platform if providers are docker or swarm.  I'll think about that.

**Comment by margaale** [comment] 2020-03-26 11:10
I think you should only in swarm mode, because you could have different architectures across the nodes. Just to note, I had never seen that error with version 2.5.0 and the config remains the same.

**Comment by crazy-max** [comment] 2020-03-26 11:24
@margaale Looks like a regression linked to containers/image#854

**Comment by crazy-max** [comment] 2020-03-26 11:55
@margaale Can you open a new bug report about that please?

**Comment by margaale** [comment] 2020-03-26 12:04
@crazy-max Sure. Just to clarify what do you mean with my stack config?

**Comment by crazy-max** [comment] 2020-03-26 12:05
@margaale

> Sure

Thanks!

> Just to clarify what do you mean with my stack config?

Your yml compose

**Comment by margaale** [comment] 2020-03-26 12:08
@crazy-max You mean the one that defines the stack that runs diun? I have several composes :-P

**Comment by crazy-max** [comment] 2020-03-26 12:09
@margaale grafana stack
